package com.whatis

object LocalAnswerStore {
    val answers = mapOf(
        "airplane" to "An airplane flies high in the sky. It has wings and goes zoom! You ride it to faraway places.",
        "ambulance" to "An ambulance is a fast car with flashing lights and loud sounds. It helps people who are hurt. It takes them to the doctor quickly.",
        "animal" to "An animal is a living creature like a dog, cat, or elephant. Animals can walk, fly, or swim. We love to see them!",
        "ant" to "An ant is a tiny bug that crawls on the ground. It carries food and lives in big families. Ants are strong for their size!",
        "apple juice" to "Apple juice is a sweet drink made from apples. It's yummy and golden. You drink it from a cup or bottle.",
        "apple" to "An apple is a crunchy fruit that's red, green, or yellow. It's sweet and yummy. You can eat it as a snack!",
        "aunt" to "An aunt is your mommy or daddy's sister. She gives kisses and plays games. Aunts are very sweet!",
        "baby" to "A baby is a tiny person who drinks milk and sleeps a lot. Babies smile and giggle. You can help take care of them!",
        "ball" to "A ball is round and bouncy. You can throw it, kick it, or roll it. Playing with a ball is lots of fun!",
        "banana" to "A banana is a yellow fruit you peel before eating. It's soft and sweet inside. Monkeys love them too!",
        "bat" to "A bat is a night animal that flies. It has wings like a cape. Bats sleep upside down!",
        "bathtub" to "A bathtub is where you take a bath. You sit in it and splash with water and toys. It helps you get clean!",
        "bear" to "A bear is a big furry animal. It can stand on two legs and loves honey. Bears sleep a lot in the winter!",
        "bed" to "A bed is where you lie down to sleep. It has a soft pillow and blanket. You rest in it every night.",
        "bee" to "A bee is a tiny flying bug that goes buzz. It helps flowers grow. Bees make yummy honey!",
        "bell" to "A bell rings and goes ding-ding! You can shake it or ring it. Bells are used in songs and games!",
        "bib" to "A bib goes around your neck at mealtime. It catches food and keeps your shirt clean. It's like a tiny apron!",
        "bike" to "A bike has two wheels and pedals. You ride it with a helmet. It's fun and fast!",
        "bird" to "A bird has feathers and wings. It can fly in the sky. Birds sing songs and build nests.",
        "blanket" to "A blanket is soft and keeps you warm. You snuggle under it when you sleep. It feels cozy!",
        "block" to "A block is a small shape you can stack. You build towers or houses. Blocks come in many colors!",
        "blueberry" to "Blueberries are tiny and blue. They're sweet and fun to eat. You can put them in pancakes or yogurt!",
        "boat" to "A boat floats on water and takes people across rivers or seas. It can have sails or motors. You can ride one on a lake!",
        "book" to "A book has pages with words and pictures. You read it to hear stories. Books can make you smile or laugh!",
        "bottle" to "A bottle holds milk or juice. Babies drink from it. It has a little top to sip from!",
        "bread" to "Bread is soft and chewy. You can eat it with butter or jam. It comes in slices for sandwiches!",
        "broccoli" to "Broccoli looks like tiny green trees. It's a vegetable that helps you grow strong. You eat it with your food!",
        "brush" to "A brush is soft and smooths your hair. It has bristles that move through your hair. It feels nice!",
        "bus" to "A bus is a big car that takes lots of people places. It has many seats and big windows. You can ride it to school!",
        "butterfly" to "A butterfly is a flying bug with colorful wings. It flutters from flower to flower. It's very gentle and pretty.",
        "cake" to "Cake is a soft, sweet dessert. We eat it on birthdays and parties. It can have icing and sprinkles!",
        "camera" to "A camera takes pictures of people and things. You smile, and it goes click! It saves happy moments.",
        "car" to "A car is something we ride in to go places. It has wheels and goes vroom! You sit in your seat with a seatbelt.",
        "carrot" to "A carrot is a crunchy orange vegetable. Bunnies love to eat it. It grows in the ground!",
        "cat" to "A cat is a soft animal that says meow. It likes to sleep and purr. Sometimes it chases toys or mice.",
        "ceiling" to "The ceiling is the top of the room. It's above your head. Sometimes lights hang from it!",
        "cereal" to "Cereal is crunchy food you eat with milk. It comes in fun shapes and colors. You eat it for breakfast!",
        "chair" to "A chair is something you sit on. It has legs and a back. You use it when you eat or draw!",
        "cheese" to "Cheese is yellow or white and tastes yummy. It goes on sandwiches or crackers. Mice love cheese too!",
        "chicken" to "A chicken is a bird that lives on a farm. It goes cluck and lays eggs. Baby chickens are called chicks!",
        "classroom" to "A classroom is a room in school where you learn. It has books, toys, and a teacher. You sit and listen there!",
        "clock" to "A clock tells you what time it is. It has numbers and hands that move. Some clocks go tick-tock!",
        "cloud" to "Clouds are soft and fluffy in the sky. Sometimes they are white, sometimes they are gray. They bring rain too!",
        "color" to "Color makes things look bright and fun. Red, blue, yellow—there are so many! You can color anything you like!",
        "comb" to "A comb has teeth and helps fix your hair. You pull it gently through your hair. It makes you look neat!",
        "computer" to "A computer is a machine that helps people work and play. It can show videos and games. You use a keyboard and mouse with it!",
        "cookie" to "A cookie is a small, round treat. It's sweet and crunchy. Some cookies have chocolate chips!",
        "corn" to "Corn is a yellow vegetable with little kernels. It grows on a tall plant. You can eat it on a stick or in popcorn!",
        "cousin" to "A cousin is your family friend who is like a buddy. You play and share toys. Cousins are fun to visit!",
        "cow" to "A cow is a big animal that gives us milk. It goes moo and eats grass. Cows live on farms!",
        "crayon" to "A crayon is a colorful stick for drawing. You hold it and make pictures. Crayons come in many fun colors!",
        "cucumber" to "A cucumber is green and long. It's cool and crunchy. You can eat it raw or in salads!",
        "daddy" to "Daddy is your big helper and best buddy. He plays with you and gives big hugs. He loves you very much!",
        "deer" to "A deer is a gentle animal with long legs. It runs fast and has antlers. Deer live in the forest!",
        "diaper" to "A diaper goes on your bottom and keeps you dry. Babies wear them. Grown-ups help you change it!",
        "doctor" to "A doctor helps you feel better when you're sick. They check your heartbeat and give medicine. Doctors wear coats and smile a lot!",
        "dog" to "A dog is a furry friend that barks. It loves to play and wag its tail. Some dogs like to cuddle too!",
        "doll" to "A doll looks like a tiny person. You can dress it and play with it. It's fun to care for your doll!",
        "dolphin" to "A dolphin is a smart animal that swims in the sea. It jumps and makes fun sounds. Dolphins love to play!",
        "door" to "A door opens and closes to let you in or out. You can knock on it or turn the handle. It keeps you safe inside!",
        "drawing" to "A drawing is a picture you make. You can use crayons, pencils, or paint. It shows what's in your mind!",
        "drum" to "A drum makes a boom-boom sound. You hit it with sticks or hands. It's loud and fun!",
        "duck" to "A duck is a bird that swims in water. It goes quack-quack and has webbed feet. Ducks like to waddle and splash.",
        "eagle" to "An eagle is a strong bird that flies high. It has sharp eyes and big wings. Eagles are great hunters!",
        "egg" to "An egg is round and comes from a chicken. It's white or brown outside and yellow inside. You can eat it or see baby animals grow in it!",
        "elephant" to "An elephant is a big animal with a long trunk. It uses its trunk to drink water and pick things up. It has big ears and likes to splash in water.",
        "elevator" to "An elevator is a little room that goes up and down in buildings. You press a button and it takes you to another floor!",
        "fan" to "A fan blows cool air when you're hot. It spins fast and makes a soft sound. It helps you feel better on warm days!",
        "fire truck" to "A fire truck is big and red with a loud siren. It carries firefighters and water. It helps stop fires!",
        "fish" to "A fish is a little animal that lives in water. It swims with its fins. Some are colorful and shiny!",
        "floor" to "The floor is what you walk on. You can sit, crawl, or play on it. Keep your toys there!",
        "flower" to "A flower is a pretty plant with colorful petals. It smells nice. Bees and butterflies love it!",
        "fox" to "A fox is a small animal with a fluffy tail. It's clever and quick. Foxes live in the woods.",
        "friend" to "A friend is someone you like to play with. You share toys and laugh together. Friends make you happy!",
        "frog" to "A frog is a green animal that jumps high. It says ribbit and lives near water. Frogs love to hop!",
        "game" to "A game is something fun you play. Some games you play alone, some with friends. Games help you learn and laugh!",
        "giraffe" to "A giraffe is very tall with a long neck. It eats leaves from tall trees. It has spots all over its body!",
        "glue" to "Glue is sticky and helps things stay together. You squeeze it to stick paper or shapes. Let it dry!",
        "goat" to "A goat is a funny animal with little horns. It goes maa and climbs on things. It loves to nibble grass!",
        "grandma" to "Grandma is your mommy or daddy's mommy. She gives hugs and cookies. She loves to spend time with you!",
        "grandpa" to "Grandpa is your mommy or daddy's daddy. He tells fun stories and gives big hugs. He's super kind!",
        "grape" to "Grapes are small and round. They can be purple or green. You can eat them one by one!",
        "guitar" to "A guitar has strings you strum. It makes pretty sounds. You can play music with it!",
        "hat" to "A hat goes on your head. It keeps you warm or blocks the sun. Some hats are silly and fun!",
        "horn" to "A horn is loud and used in cars. It goes beep or honk! It tells people to move or look.",
        "horse" to "A horse is a big animal with long legs. It says neigh and runs fast. You can ride on it!",
        "kangaroo" to "A kangaroo hops with big legs and carries its baby in a pouch. It lives far away in a place called Australia. It's very bouncy!",
        "koala" to "A koala is a sleepy animal that lives in trees. It eats leaves and cuddles branches. It looks like a teddy bear!",
        "ladybug" to "A ladybug is a red bug with black spots. It flies and lands on flowers. It's tiny and friendly!",
        "lamp" to "A lamp gives you light when it's dark. You turn it on with a switch. It can be tall or small!",
        "laptop" to "A laptop is a small computer you can carry. You open and close it like a book. It can go with you anywhere!",
        "lego" to "Lego are little blocks that snap together. You can build anything—cars, castles, or animals. Use your imagination!",
        "lettuce" to "Lettuce is a green leafy vegetable. It's crunchy and cool. You eat it in salads or sandwiches!",
        "lion" to "A lion is a big wild cat with a loud roar. It has a fluffy mane. Lions are very strong!",
        "milk" to "Milk is a white drink that comes from cows. It helps your bones grow strong. You drink it in your bottle or cup.",
        "mirror" to "A mirror shows your face like a picture. You can make funny faces in it. It's shiny like glass!",
        "mommy" to "Mommy is your special grown-up who loves you. She helps you, hugs you, and takes care of you every day.",
        "monkey" to "A monkey is a playful animal that swings on trees. It makes funny sounds and loves bananas. Monkeys are very smart!",
        "moon" to "The moon is round and shiny in the sky at night. Sometimes it's big, sometimes it's tiny. It watches while we sleep.",
        "mouse" to "A mouse is a small furry animal. It squeaks and runs fast. Mice like cheese!",
        "music" to "Music is sound that makes you feel happy or dance. You can sing, clap, or play to the beat. Music is everywhere!",
        "nest" to "A nest is a cozy little home for baby birds. Mommy bird puts it in a tree. It's made of twigs and leaves.",
        "nurse" to "A nurse helps the doctor and takes care of people. They give hugs and bandages. Nurses are kind and helpful!",
        "octopus" to "An octopus lives in the ocean and has eight arms. It can squirt ink and hide in rocks. It's very wiggly!",
        "onion" to "An onion is a round vegetable with layers. It can make your eyes watery! It's used to cook many yummy foods.",
        "orange" to "An orange is a round, juicy fruit. You peel it to eat it. It's sweet and full of juice!",
        "owl" to "An owl is a bird that stays up at night. It has big eyes and goes hoot! It can see in the dark.",
        "paint" to "Paint is colorful and wet. You use a brush to make pictures. It can be messy but fun!",
        "panda" to "A panda is a big black and white bear. It eats bamboo and rolls around. Pandas are soft and cute!",
        "paper" to "Paper is flat and white. You draw, color, or write on it. It's used for crafts and stories!",
        "peach" to "A peach is soft and fuzzy outside. It's sweet and juicy inside. It's a yummy summer fruit!",
        "pen" to "A pen writes with ink. It's smooth and fun to use. The lines stay even if you touch them!",
        "pencil" to "A pencil is for writing or drawing. It has a pointy end and a little eraser. You can change what you draw!",
        "pepper" to "A pepper can be red, yellow, green, or orange. It's crunchy and colorful. Some are sweet, some are spicy!",
        "phone" to "A phone lets you talk to people far away. You can see pictures and videos on it. Grown-ups use it a lot!",
        "piano" to "A piano has black and white keys. You press them to make music. It sounds beautiful!",
        "pig" to "A pig is a round animal that goes oink. It likes mud and sniffs around with its nose. Baby pigs are called piglets!",
        "pillow" to "A pillow is soft and fluffy. You put your head on it at bedtime. It helps you sleep better!",
        "playground" to "A playground is a place outside with slides and swings. You run, jump, and play with friends. It's super fun!",
        "plum" to "A plum is a small round fruit that's sweet and juicy. It's purple outside and soft inside. You can eat it as a snack!",
        "police car" to "A police car is a fast car with lights and sirens. Police officers use it to help people. It keeps everyone safe!",
        "potato" to "A potato is a brown vegetable that grows underground. It can be mashed, baked, or made into fries. It's yummy!",
        "pumpkin" to "A pumpkin is big and orange. It grows on the ground. You can make pies or jack-o'-lanterns with it!",
        "puzzle" to "A puzzle has pieces that fit together to make a picture. You find the right pieces and put them in place. It's like a fun mystery!",
        "rabbit" to "A rabbit has long ears and hops. It's soft and cuddly. Rabbits love to munch on carrots!",
        "railway" to "A railway is a long path with tracks for trains. It connects cities and places. Trains ride along it every day!",
        "rain" to "Rain is water that falls from the sky. It makes puddles you can jump in. Don't forget your umbrella!",
        "rat" to "A rat is like a big mouse. It has a long tail and likes to explore. Rats are very smart!",
        "remote" to "A remote helps you change the TV from far away. You press buttons to pick shows. It's like a magic stick!",
        "road" to "A road is where cars and trucks drive. It has lines to show where to go. Roads take you places!",
        "robot" to "A robot is a machine that can move and beep. Some talk or light up. Robots are cool and fun to watch!",
        "roof" to "A roof covers the top of a house. It keeps out the rain and sun. It's like a hat for your home!",
        "sandbox" to "A sandbox is a box full of soft sand. You can dig, scoop, and build with it. It's like the beach!",
        "school" to "School is a place where you go to learn and play. You meet friends and sing songs. School is full of fun!",
        "scissors" to "Scissors help you cut paper. You open and close them like a mouth. Be careful and ask a grown-up to help!",
        "scooter" to "A scooter has two wheels and a handle. You stand on it and push with your foot. Whee, you go fast!",
        "shampoo" to "Shampoo is like soap for your hair. It makes lots of bubbles. It keeps your head clean!",
        "shark" to "A shark is a big fish with sharp teeth. It swims in the ocean. But don't worry, they don't live in bathtubs!",
        "sheep" to "A sheep is a fluffy animal with soft wool. It goes baa and lives on a farm. Its wool keeps us warm.",
        "ship" to "A ship is a big boat that goes in the ocean. It carries lots of people or things. Some ships have rooms and beds!",
        "shoe" to "A shoe goes on your foot when you go outside. It keeps your feet safe. You wear two shoes, one for each foot!",
        "slide" to "A slide is a tall toy you climb up and slide down. Whee! It's fun and fast!",
        "snail" to "A snail is a slow creature with a shell. It crawls on the ground and leaves a shiny trail. Snails are quiet and cute!",
        "snow" to "Snow is cold and white and falls from the sky. You can make snowmen and snowballs with it. It covers everything like a blanket!",
        "soap" to "Soap makes bubbles and gets you clean. You use it on your hands and body. It smells nice too!",
        "sock" to "A sock is soft and goes on your foot before your shoe. It keeps your toes warm. Socks come in fun colors!",
        "song" to "A song is music with words. You sing it loud or soft. Songs tell stories or make you dance!",
        "spider" to "A spider is a little bug with eight legs. It spins webs to catch food. Some webs are very pretty!",
        "squirrel" to "A squirrel is a furry animal with a bushy tail. It climbs trees and eats nuts. It jumps from branch to branch!",
        "stairs" to "Stairs help you go up and down. You walk one step at a time. Hold the railing for safety!",
        "star" to "Stars are tiny twinkles in the night sky. They shine like little lights. You can wish on a star!",
        "starfish" to "A starfish is shaped like a star and lives in the sea. It moves slowly and sticks to things. It has no face but is very cool!",
        "strawberry" to "A strawberry is a red fruit with tiny seeds outside. It's sweet and heart-shaped. You can eat it in desserts!",
        "submarine" to "A submarine is a boat that goes under the water. It has windows to see fish. It's like a secret sea car!",
        "sun" to "The sun is big and bright in the sky. It gives us light and keeps us warm. It comes out in the morning to say hello!",
        "swing" to "A swing goes back and forth while you sit. You hold the ropes and fly in the air. It's like flying!",
        "table" to "A table is where we put our food, toys, or books. It has legs and a flat top. You sit at it to eat or play!",
        "tablet" to "A tablet is like a small screen you can touch. You watch videos or play games on it. It's light and fun!",
        "teacher" to "A teacher helps you learn new things. They read stories and play games with you. Teachers are very smart and fun!",
        "teddy bear" to "A teddy bear is a soft toy you can hug. It has arms, legs, and a little nose. It's your cuddly friend!",
        "television" to "A television is a big screen that shows cartoons and songs. You sit and watch with your family. It has fun lights and sounds!",
        "tiger" to "A tiger is a big cat with orange fur and black stripes. It moves quietly and lives in forests. Tigers love to rest in the shade.",
        "tomato" to "A tomato is red and round. It's juicy and can go in salads or sauces. It grows on a plant!",
        "toothbrush" to "A toothbrush helps clean your teeth. You move it up and down in your mouth. Use it with toothpaste!",
        "toothpaste" to "Toothpaste is a minty gel for brushing teeth. It helps keep your mouth clean. You put a little on your brush!",
        "towel" to "A towel is soft and helps you dry after a bath. You wrap it around you. It comes in fun colors!",
        "toy" to "A toy is something you play with. It can be soft, noisy, or light up. Toys make you smile!",
        "traffic light" to "A traffic light tells cars when to stop and go. Red means stop, green means go. It helps everyone stay safe!",
        "train track" to "Train tracks are metal paths trains follow. They go straight or curve. Trains ride safely on them!",
        "train" to "A train is a long vehicle that rides on tracks. It goes choo-choo and carries people and things. You can see it at the station!",
        "tree" to "A tree is tall with a trunk and green leaves. Birds sit in it, and it gives us shade. Some trees grow fruit!",
        "truck" to "A truck is a big vehicle that carries things. It has large wheels and goes vroom! Trucks can be red, blue, or yellow!",
        "trumpet" to "A trumpet is a shiny horn you blow into. It goes toot-toot! It's loud and fun to play!",
        "tunnel" to "A tunnel is a long hole under or through something. Cars or trains go inside it. It's dark but fun to go through!",
        "uncle" to "An uncle is your mommy or daddy's brother. He plays with you and makes you laugh. Uncles are fun!",
        "violin" to "A violin is a small string instrument. You move a stick across it to play. It makes soft music.",
        "wall" to "A wall stands up and makes a room. You can hang pictures on it. It holds up the roof too!",
        "water" to "Water is what we drink when we're thirsty. It's clear and cool. You can splash in it during bath time!",
        "watermelon" to "A watermelon is big and green outside, red and juicy inside. It has black seeds. It's fun to eat in summer!",
        "whale" to "A whale is a giant animal that lives in the ocean. It sings songs and sprays water from its head. Whales are very gentle!",
        "whistle" to "A whistle makes a sharp sound when you blow it. It goes tweet! Coaches and referees use it.",
        "window" to "A window lets you see outside. You can open it for fresh air. It's made of glass and shines in the sun!",
        "wolf" to "A wolf is like a big wild dog. It howls at night. Wolves live in groups called packs!",
        "worm" to "A worm is a tiny squiggly creature that lives in the dirt. It wiggles when it moves. Worms help plants grow!",
        "yogurt" to "Yogurt is soft and creamy. It comes in many flavors and is good for your tummy. You eat it with a spoon!",
        "zebra" to "A zebra looks like a horse with black and white stripes. It lives in the wild. No two zebras have the same stripes!"
    )
}